### PR TITLE
Fix typo in cors template

### PR DESCRIPTION
**Pull request by bjoshua**
- fixed xml formatting issue

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/rackerlabs/puppet-repose/pull/58" target="_blank">ReviewNinja

**Comment by classyviking** [comment]
👍  LGTM and local test of results works

**Comment by teriyakichild** [comment]
@bjoshua please bump the version in the Modulefile

**Comment by bjoshua** [comment]
@teriyakichild - updated, thanks - good catch it was out of date from last commit already.

**Comment by teriyakichild** [comment]
+1

**Comment by teriyakichild** [comment]
+1

**Pull request merged**
