### PR TITLE
First attempt at an atom feed service resource.

### PR DESCRIPTION
**Pull request by adrianjgeorge**
I tried to write some tests, but nothing i tried worked. I suspect I just don't know enough rspec to make it work.

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
My understanding is that it's based on file name, and then the order number is it's placement.
[Docs](https://github.com/puppetlabs/puppetlabs-concat)

**Comment by adrianjgeorge** [comment]
I've added some tests, but a few of them are failing, and i don't know enough to figure out what's going on. I could use a hand debugging them.

**Comment by adrianjgeorge** [comment]
@teriyakichild ^

**Comment by teriyakichild** [comment]
@adrianjgeorge Looking into this now.

**Comment by teriyakichild** [comment]
@adrianjgeorge The following patch should fix the tests:

```diff
diff --git a/.fixtures.yml b/.fixtures.yml
index 88c81cf..aaa249e 100644
--- a/.fixtures.yml
+++ b/.fixtures.yml
@@ -2,6 +2,8 @@ fixtures:
   repositories:
     stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
   forge_modules:
+    concat:
+      repo: "puppetlabs/concat"
     stdlib:
       repo: "puppetlabs/stdlib"
       ref: "2.6.0"
diff --git a/spec/defines/filter/atom_feed_service_spec.rb b/spec/defines/filter/atom_feed_service_spec.rb
index da15a76..4a5f8f5 100644
--- a/spec/defines/filter/atom_feed_service_spec.rb
+++ b/spec/defines/filter/atom_feed_service_spec.rb
@@ -14,9 +14,6 @@ describe 'repose::filter::atom_feed_service', :type => :class do
 
     context 'default parameters' do
       let(:title) { 'default' }
-      let(:params) { {
-          :ensure => 'absent'
-      } }
       it {
         should contain_concat('/etc/repose/atom-feed-service.cfg.xml').with_ensure('present')
         should contain_concat__fragment('header').with_target('/etc/repose/atom-feed-service.cfg.xml').with_order('01')
diff --git a/spec/defines/filter/atom_feed_spec.rb b/spec/defines/filter/atom_feed_spec.rb
index 4ed9521..bbfdf1d 100644
--- a/spec/defines/filter/atom_feed_spec.rb
+++ b/spec/defines/filter/atom_feed_spec.rb
@@ -57,7 +57,7 @@ describe 'repose::filter::atom_feed', :type => :define do
             with_target('/etc/repose/atom-feed-service.cfg.xml').
             with_order('50').
             with_content(/feed id="some_feed"/).
-            with_conent(/uri="http:\/\/foo.bar"/).
+            with_content(/uri="http:\/\/foo.bar"/).
             with_content(/connection-pool-id="pool_id"/).
             with_content(/entry-order="reverse-read"/).
             with_content(/uri="http:\/\/bar.foo"/).
```

**Comment by adrianjgeorge** [comment]
Thanks, inbound as soon as i have a moment.

**Comment by adrianjgeorge** [comment]
that first part was the critical bit. once things were actually running, i could have figured out the other two.

**Comment by teriyakichild** [comment]
@adrianjgeorge The current test failures are caused by the newer version of puppetlabs-concat which only supports Puppet 4 and Puppet 5.  We should update the .fixtures.yml to specify version 2.2.0 which supports Puppet 3 through Puppet 5.

**Comment by adrianjgeorge** [comment]
Thanks, i suspected it was something like that.

**Comment by teriyakichild** [comment]
For puppet2 support, we need to pin to an even older version of concat.  The following patch should resolve the currently failing tests:

```diff
diff --git a/.fixtures.yml b/.fixtures.yml
index aaa249e..3bb3330 100644
--- a/.fixtures.yml
+++ b/.fixtures.yml
@@ -4,6 +4,7 @@ fixtures:
   forge_modules:
     concat:
       repo: "puppetlabs/concat"
+      ref: "1.1.0"
     stdlib:
       repo: "puppetlabs/stdlib"
       ref: "2.6.0"
diff --git a/manifests/filter/atom_feed_service.pp b/manifests/filter/atom_feed_service.pp
index de76ff9..8d3cd18 100644
--- a/manifests/filter/atom_feed_service.pp
+++ b/manifests/filter/atom_feed_service.pp
@@ -51,13 +51,13 @@ class repose::filter::atom_feed_service (
 
   concat::fragment { 'header':
     target => "${repose::params::configdir}/atom-feed-service.cfg.xml",
-    content => file("${module_name}/atom-feed-service-header"),
+    source => "puppet:///modules/${module_name}/atom-feed-service-header",
     order   => '01',
   }
 
   concat::fragment { 'footer':
     target => "${repose::params::configdir}/atom-feed-service.cfg.xml",
-    content => file("${module_name}/atom-feed-service-footer"),
+    source => "puppet:///modules/${module_name}/atom-feed-service-footer",
     order   => '99',
   }
 }
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index 844aa68..343a38a 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -5,5 +5,6 @@ require 'rspec-puppet-utils'
 RSpec.configure do |c|
   c.default_facts = {
     :debug                     => 'true',
+    :concat_basedir            => '/tmp',
   }
 end
```

**Comment by adrianjgeorge** [comment]
i'm expecting this next one to fail, but i need the output so i can fix some things up. My local environment has gotten into a weird condition that has made running it difficult.

**Comment by adrianjgeorge** [comment]
Looks like it's broke in ruby 2 and puppet 4.5+?

**Comment by teriyakichild** [comment]
@adrianjgeorge The issue is that rspec enables strict variables for specific versions of puppet4.  Our tests are pinning concat to version 1.1.0 which does not support puppet4.  We can disable strict variables in the travis config with the following patch:

```diff
diff --git a/.travis.yml b/.travis.yml
index f2e486a..ef7b6f1 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,7 +15,7 @@ gemfile:
   - .gemfiles/Gemfile.ruby193.rspec
 
 script:
- - "bundle exec rake spec SPEC_OPTS='--format documentation'"
+ - "STRICT_VARIABLES=no bundle exec rake spec SPEC_OPTS='--format documentation'"
 
 env:
   - PUPPET_VERSION="~> 2.7.0"
```

**Comment by adrianjgeorge** [comment]
I'm pretty sure some people who are using this will want to be on puppet 4+

**Comment by teriyakichild** [comment]
@adrianjgeorge I agree this is less than ideal but these are reasons why I think this is the best path forward:
1. From Puppet 4.0 - 4.5, the default was strict_variables=true.  The default for Puppet 4.6 - 4.10 (latest version) is strict_variables=false.  Puppetlabs even removed all their documentation for Puppet 4.0-4.5.  Also, we are currently only testing against 4.5-4.8. [1]
2. To support testing against ruby 1.8.7, we are using an old version of rspec-puppet which seems to set strict variables to true for all versions of puppet 4 (This may have been fixed in new versions).
3. Our testing framework does not support using a different set of module per version of puppet/ruby which is why we have to pin to that specific version of concat.

I'd also argue that we should just remove the testing against puppet 4.5 and add support for 4.9 and 4.10.

1. https://puppet.com/docs/puppet/4.6/lang_variables.html#unassigned-variables-and-strict-mode

**Comment by adrianjgeorge** [comment]
ahh, i didn't realize it was a thing that they only did for a short time period. In that case i will make the changes shortly

**Pull request merged**
