### PR TITLE
CF-618 - HERP filter

### PR DESCRIPTION
**Pull request by usnavi**
- fixing the user access event template

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/rackerlabs/puppet-repose/pull/45" target="_blank">ReviewNinja

**Comment by usnavi** [comment]
Actually, I'll do more testing and then submit.

**Comment by gregswift** [comment]
I hate the syntax on those substitutions.. not because i care abot {{ }} in general, but because its what jinja2 (a la ansible) uses and so it confuses me every time i look at it

**Comment by usnavi** [comment]
Yeah, that's the syntax that repose is using for the filter.

**Comment by usnavi** [comment]
@gregswift  - any other issues which need to be addressed before this is accepted?

**Pull request merged**
