### PR TITLE
fix spec tests first

### PR DESCRIPTION
**Pull request by shintasmith**
This fixes the broken spec tests

### CODE REVIEW

**Comment by mwhahaha** [comment]
@shintasmith upgrade your puppet-rspec, these were already fixed once to use the new version of puppet-rspec, https://github.com/rackerlabs/puppet-repose/pull/25/.  Also, Hi :)

**Comment by shintasmith** [comment]
@mwhahaha!!!!! Good to hear from you! Hi. How was Ukraine? ;-)

Well.... no one told me about the rspec-puppet. I will update the Readme to specificly say it requires the new version. Thx!

**Comment by usnavi** [comment]
Wa!!!!!  Hey, we could use some help updating the staging puppetmaster... :-D

**Comment by shintasmith** [comment]
@mwhahaha, no good. I already have rspec-puppet 2.2.0 and it didn't work.
```
MJV0BAFCQ3:puppet-repose shin4590$ gem list

*** LOCAL GEMS ***
...
rspec-puppet (2.2.0)
```

**Comment by mwhahaha** [comment]
Ruby make me sad some times.  But this works:

```
rvm use ruby-2.1.5@repose --create
gem install rspec-core:3.1.7 puppet:3.7.4 rspec-puppet rspec-puppet-utils puppetlabs_spec_helper puppet-lint rake --no-ri --no-rdoc
rake spec
```

results in:
```
/Users/aschultz/.rvm/rubies/ruby-2.1.5/bin/ruby -I/Users/aschultz/.rvm/gems/ruby-2.1.5@repose/gems/rspec-support-3.2.2/lib:/Users/aschultz/.rvm/gems/ruby-2.1.5@repose/gems/rspec-core-3.2.3/lib /Users/aschultz/.rvm/gems/ruby-2.1.5@repose/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
.....................................................................................................................................................................

Finished in 14.51 seconds (files took 0.7619 seconds to load)
165 examples, 0 failures
```

Gem list
```
*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.7.6)
bundler-unload (1.0.2)
CFPropertyList (2.2.8)
diff-lcs (1.2.5)
executable-hooks (1.3.2)
facter (2.4.4 universal-darwin)
gem-wrappers (1.2.7)
hiera (1.3.4)
io-console (0.4.2)
json (1.8.1)
json_pure (1.8.2)
metaclass (0.0.4)
minitest (4.7.5)
mocha (1.1.0)
psych (2.0.5)
puppet (3.7.4)
puppet-lint (1.1.0)
puppet-syntax (2.0.0)
puppetlabs_spec_helper (0.10.3)
rake (10.4.2, 10.1.0)
rdoc (4.1.0)
rspec (3.2.0)
rspec-core (3.2.3, 3.1.7)
rspec-expectations (3.2.1)
rspec-mocks (3.2.1)
rspec-puppet (2.2.0)
rspec-puppet-utils (2.0.6)
rspec-support (3.2.2, 3.1.2)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (2.1.5.0)
```

**Comment by shintasmith** [comment]
@mwhahaha, thx a bunch! Works for me now. Yes, ruby makes me sad too. I will close this one and update the Readme with the right info in the next PR.

**Pull request closed without merging**
